### ISSUE TITLE
Some error about the sgrid

### ISSUE THREAD

**Issue by Mr-Bey** [zerothi/sisl#68]
Dear Nick,

Thanks for checking this message.

When I enter the script sgrid, the following error message will be output on the screen. I do not understand what this message means.

$ sgrid --help

 Traceback (most recent call last):
  File "/home/lee/anaconda3/bin/sgrid", line 11, in <module>
    load_entry_point('sisl==0.9.2', 'console_scripts', 'sgrid')()
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/grid.py", line 846, in sgrid
    with get_sile(input_file) as fh:
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/io/sile.py", line 271, in get_sile
    sile = get_sile_class(file, *args, cls=cls, **kwargs)
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/io/sile.py", line 182, in get_sile_class
    tmp_file, fcls = str_spec(file)
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/utils/misc.py", line 138, in str_spec
    if not name.endswith('}'):
AttributeError: 'NoneType' object has no attribute 'endswith'

I am not very good at programming, Is this caused by my incorrect operation?
I'm trying to convert a grid file to CUBE fileIs by using 'sgrid Rho.grid.nc Rho.cube'. May I have your suggestions?
And I have try to use sgeom and sdata , they work. Maybe it has some bug about sgrid?

Yours Sincerely!

Lee

**Comment by zerothi** [comment]
Sadly, there were some bugs in 0.9.2 related to the scripts.

These has been fixed. You could try and manually install the development version of sisl. That should solve your problems.

**Comment by zerothi** [comment]
Please follow these instructions:

http://sisl.readthedocs.io/en/latest/installation.html#manual-installation

In particular you need to clone the git repository or download the latest zip (there is a green button named "Clone or download" on the [sisl](github.com/zerothi/sisl)

**Comment by Mr-Bey** [comment]
Actually I installed sisl by the command ‘git clone https://github.com/zerothi/sisl.git’ before. And install it by the command 'pip install ./sisl'.

I tryed the lastest development version by manually install just now. However, the sgrid is still not work. But the sgeom and sdata operating normally .

Here is the version information：
sisl: 0.9.2+504 + 504
revision: acc3e5cd959303cc3ad3a8c97a68d4a36d3c1579

**Comment by zerothi** [comment]
I can successfully run `sgrid Rho.grid.nc Rho.cube` on a test system, could you show the (new?) error?

**Comment by zerothi** [comment]
So if you run `sgrid --version` you get the information above?

**Comment by Mr-Bey** [comment]
I can get the information above by runing `sdata --version` or `sgeom --version`. When I run `sgrid --version` , the errors encountered are consistent with those before.

Traceback (most recent call last):
  File "/home/lee/anaconda3/bin/sgrid", line 11, in <module>
    load_entry_point('sisl==0.9.2', 'console_scripts', 'sgrid')()
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/grid.py", line 846, in sgrid
    with get_sile(input_file) as fh:
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/io/sile.py", line 271, in get_sile
    sile = get_sile_class(file, *args, cls=cls, **kwargs)
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/io/sile.py", line 182, in get_sile_class
    tmp_file, fcls = str_spec(file)
  File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl/utils/misc.py", line 138, in str_spec
    if not name.endswith('}'):
AttributeError: 'NoneType' object has no attribute 'endswith'

when runing `sgrid Rho.grid.nc Rho.cube`, It is also this error above.

I install sisl in the Anaconda environment, Is this one of the influencing factors of error?

**Comment by zerothi** [comment]
Could you try and install sisl (from the cloned directory) using this command
```
python3 setup.py install
```
It seems that sgrid is still referring to the old version.

**Comment by Mr-Bey** [comment]
The same error. This operation did not work. :(

**Comment by zerothi** [comment]
It means that you haven't succesfully installed the latest `sisl` version.
Please try and delete the old installation before trying again.

You could also try to do `sudo` installation.

**Comment by Mr-Bey** [comment]
OK , I'll try it again.

Thank you sooooo much!

**Comment by Mr-Bey** [comment]
Hi Nick,
I followed your advice, rolled back the Ubuntu system and installed the latest development version of sisl from scratch.

It still has some errors. Error message and before a little different.

> Traceback (most recent call last):
>   File "/home/lee/anaconda3/bin/sgrid", line 11, in <module>
>     load_entry_point('sisl==0.9.2+504', 'console_scripts', 'sgrid')()
>   File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl-0.9.2+504-py3.6-linux-x86_64.egg/sisl/grid.py", line 1316, in sgrid
>     input_file, spec = str_spec(input_file)
>   File "/home/lee/anaconda3/lib/python3.6/site-packages/sisl-0.9.2+504-py3.6-linux-x86_64.egg/sisl/utils/misc.py", line 138, in str_spec
>     if not name.endswith('}'):
> AttributeError: 'NoneType' object has no attribute 'endswith'

This is my system version, it may give some message.

> Linux version 4.4.0-31-generic (buildd@lgw01-43) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016

**Comment by zerothi** [comment]
Please also show the command line you issued for you to see this error.

**Comment by Mr-Bey** [comment]
the command I run is:
`sgrid --help`

**Comment by zerothi** [comment]
Ok, the help doesn't work, but running `sgrid Rho.grid.nc Rho.cube` should work, try it

**Comment by Mr-Bey** [comment]
A new error message coming. :(

`sgrid graphene_scat.TBT.nc graphene.cube`

>  Traceback (most recent call last):
>   File "/home/lee/anaconda3/envs/data/bin/sgrid", line 11, in <module>
>     load_entry_point('sisl==0.9.2+504', 'console_scripts', 'sgrid')()
>   File "/home/lee/anaconda3/envs/data/lib/python3.5/site-packages/sisl-0.9.2+504-py3.5-linux-x86_64.egg/sisl/grid.py", line 1329, in sgrid
>     grid = get_sile(input_file).read_grid(**kwargs)
>   File "/home/lee/anaconda3/envs/data/lib/python3.5/site-packages/sisl-0.9.2+504-py3.5-linux-x86_64.egg/sisl/io/sile.py", line 400, in __getattr__
>     return getattr(self.fh, name)
>   File "netCDF4/_netCDF4.pyx", line 2388, in netCDF4._netCDF4.Dataset.__getattr__ (netCDF4/_netCDF4.c:20474)
>   File "netCDF4/_netCDF4.pyx", line 2333, in netCDF4._netCDF4.Dataset.getncattr (netCDF4/_netCDF4.c:19433)
>   File "netCDF4/_netCDF4.pyx", line 1112, in netCDF4._netCDF4._get_att (netCDF4/_netCDF4.c:4451)
> AttributeError: NetCDF: Attribute not found

Does It mean that there's something wrong with netCDF4?

**Comment by zerothi** [comment]
the tbt.nc file does not contain grid information.

**Comment by zerothi** [comment]
The latest commit has fixed the issue with `sgrid --help`, thanks for the bug-report.

I will consider this resolved, otherwise let me know.

**Comment by Mr-Bey** [comment]
Oops! This is the key to my issue!!

I have successfully got the cube file, I'm so sorry that I wasted your time because of my inferior mistake.

Thank you a lot for your careful guidance!

**Comment by zerothi** [comment]
@Mr-Bey happy sisl'ing ;)
